# Generated by Django 6.0.4 on 2026-05-04 02:35

import django.db.models.deletion
import kororinpa_stage_hub.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stage_data', kororinpa_stage_hub.fields.StageField()),
                ('released', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modified', models.BooleanField(default=False)),
                ('embed', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('music', models.PositiveSmallIntegerField(choices=[(1, 'Kororinpa Welcome'), (2, "Anthony's House"), (3, 'View The Planets'), (4, 'Kororinpa Practice'), (5, "In the Ant's Nest"), (6, 'Shiny Ranking'), (7, 'Secret Room'), (8, 'Junk Factory'), (9, 'Kororinpa Create'), (10, "Let's Choose"), (11, 'Look Closely'), (12, 'Yay! Goal!'), (13, 'Score Update'), (14, 'Explore the Empty Lot'), (15, 'Keep on Going'), (16, 'Exciting'), (17, 'Sweet Home'), (18, 'In the House'), (19, 'Mini Field Day'), (20, 'Heat Haze'), (21, 'Desert Wandering'), (22, 'Hot Plains'), (23, 'Snowy World'), (24, 'Under Aurora'), (25, 'Bullets on Ice'), (26, 'Mystic Seabed'), (27, 'Silent World'), (28, 'Peaceful Seabed'), (29, 'Station'), (30, 'Endless Space'), (31, 'Space Roller'), (32, 'Holy Corridor'), (33, 'In the Temple'), (34, 'Endless Power'), (35, 'Candy Circus'), (36, 'Cookie Dash'), (37, 'Spook Dance'), (38, 'Spook Chase'), (39, 'Into Darkness'), (40, 'Lurking in the Dark'), (41, 'Spin Town'), (42, 'Flying Highway'), (43, 'Sleepless City'), (44, 'Night Wandering'), (45, "Anthony's Request"), (46, 'Factory Notice'), (47, 'To Stump Temple'), (48, 'Long Journey End'), (49, 'Adventure Begins'), (50, 'Credits'), (51, 'Special Credits'), (52, 'The End'), (53, 'Road Runner'), (54, 'Princess Tomato'), (55, 'Bomber King'), (56, 'Star Solider'), (57, 'Walk in the Park')], default=9)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('updated__gte', models.F('released'))), name='updated_after_released'), models.CheckConstraint(condition=models.Q(('music__gt', 0), ('music__lte', 57)), name='music_in_range')],
            },
        ),
    ]
