# Generated by Django 6.0.5 on 2026-05-13 04:51

from typing import cast

from django.apps import registry
from django.db import migrations, models
from django.db.backends.base import schema


class Migration(migrations.Migration):

    @staticmethod
    def merge_updated_modified(
        apps: registry.Apps, schema_editor: schema.BaseDatabaseSchemaEditor
    ) -> None:
        cast(
            models.Model, apps.get_model("kororinpa_stage_hub", "Submission")
        ).objects.using(schema_editor.connection.alias).filter(modified=False).update(
            updated=models.F("released")
        )

    dependencies = [
        (
            "kororinpa_stage_hub",
            "0003_alter_submission_modified_alter_submission_music",
        ),
    ]

    operations = [migrations.RunPython(merge_updated_modified)]
