# Generated by Django 6.0.5 on 2026-05-13 05:00

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kororinpa_stage_hub", "0004_auto_20260513_0451"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="modified",
        ),
        migrations.AlterField(
            model_name="submission",
            name="released",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(),
                default=django.db.models.functions.datetime.Now(),
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="updated",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(),
                default=django.db.models.functions.datetime.Now(),
            ),
        ),
    ]
