# Generated by Django 6.1.1 on 2026-09-14 19:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kororinpa_stage_hub', '0005_remove_submission_modified_alter_submission_released_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submission',
            new_name='Stage',
        ),
    ]
